# Generated by Django 5.0 on 2023-12-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=50)),
                ("student_id", models.CharField(max_length=50)),
                ("year_level", models.CharField(max_length=50)),
                ("course", models.CharField(max_length=50)),
                ("department", models.CharField(max_length=50)),
                ("time", models.TimeField()),
                ("date", models.DateField()),
            ],
        ),
    ]
