# Generated by Django 5.0 on 2023-12-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="disabled",
            field=models.BooleanField(default=False),
        ),
    ]
